feature: ci-test: get correct version and checkout to tag commit

diff --git a/.ci/pipeline/docs.yml b/.ci/pipeline/docs.yml
--- a/.ci/pipeline/docs.yml
+++ b/.ci/pipeline/docs.yml
@@ -54,6 +54,33 @@ jobs:
     inputs:
       versionSpec: '3.11'
       addToPath: true
+  - script: |
+      # Extract the version from the triggering tag
+      DOC_VERSION=$(git describe --tags --abbrev=0)
+      echo "DOC_VERSION1: $DOC_VERSION"
+      # If no tag is found, fetch the latest version from PyPI
+      if [ -z "$DOC_VERSION" ]; then
+          DOC_VERSION=$(curl -s https://pypi.org/pypi/scikit-learn-intelex/json | jq -r '.info.version')
+          echo "DOC_VERSION2: $DOC_VERSION"
+      # Still cannot find version generate error
+      if [ -z "$DOC_VERSION" ]; then
+        echo "ERROR: Failed to determine documentation version."
+        exit 1
+      fi
+    displayName: 'Get correct doc version'
+  - script: |
+    # Checkout the correct commit based on the tag
+    git fetch --tags origin
+    # Get commit id and checkout to the commit that has doc version tag
+    if git rev-parse "refs/tags/$DOC_VERSION" >/dev/null 2>&1; then
+        echo "Tag $DOC_VERSION exists. Checking out the corresponding commit..."
+        git checkout tags/$DOC_VERSION
+    else
+        echo "ERROR: Tag $DOC_VERSION does not exist."
+        exit 1
+    fi
+  displayName: 'Checkout to corresponding release commit'
+
   - script: sudo apt-get update && sudo apt-get install -y clang-format pandoc 
     displayName: 'apt-get'
   - script: |
