ci-test: print

diff --git a/.ci/pipeline/docs.yml b/.ci/pipeline/docs.yml
--- a/.ci/pipeline/docs.yml
+++ b/.ci/pipeline/docs.yml
@@ -71,18 +71,18 @@ jobs:
       fi
       echo "doc version can be found"
     displayName: 'Get correct doc version'
-  # - script: |
-  #   # Checkout the correct commit based on the tag
-  #   git fetch --tags origin
-  #   # Get commit id and checkout to the commit that has doc version tag
-  #   COMMIT_HASH=$(git rev-list -n 1 $DOC_VERSION 2>/dev/null)
-  #   if [ -z "$COMMIT_HASH" ]; then
-  #       echo "ERROR: Tag $DOC_VERSION does not exist."
-  #       exit 1
-  #   fi
-  #   git checkout --detach $COMMIT_HASH
-  #   echo "can get to the correct commit"
-  # displayName: 'Checkout to corresponding release commit'
+  - script: |
+    # Checkout the correct commit based on the tag
+    git fetch --tags origin
+    # Get commit id and checkout to the commit that has doc version tag
+    COMMIT_HASH=$(git rev-list -n 1 $DOC_VERSION 2>/dev/null)
+    if [ -z "$COMMIT_HASH" ]; then
+        echo "ERROR: Tag $DOC_VERSION does not exist."
+        exit 1
+    fi
+    # git checkout --detach $COMMIT_HASH
+    echo "can get to the correct commit"
+  displayName: 'Checkout to corresponding release commit'
 
   - script: sudo apt-get update && sudo apt-get install -y clang-format pandoc 
     displayName: 'apt-get'
