ci-test: print

diff --git a/.ci/pipeline/docs.yml b/.ci/pipeline/docs.yml
--- a/.ci/pipeline/docs.yml
+++ b/.ci/pipeline/docs.yml
@@ -78,8 +78,8 @@ jobs:
       cat build.log
       # check for autodoc warnings
       if grep -i "autodoc" build.log; then
-          echo "Autodoc Warnings detected, build failed!"
-          exit 1
+        echo "Autodoc Warnings detected, build failed!"
+        exit 1
     displayName: 'Build daal4py documentation'
   - script: |
       export PREFIX=$(dirname $(dirname $(which python)))
