fix: move warning detect from makefile to build-doc.sh and yml

diff --git a/.ci/pipeline/docs.yml b/.ci/pipeline/docs.yml
--- a/.ci/pipeline/docs.yml
+++ b/.ci/pipeline/docs.yml
@@ -74,7 +74,12 @@ jobs:
       export DALROOT=$PREFIX
       export LD_LIBRARY_PATH=$(dirname $(dirname $(which python)))/lib:$LD_LIBRARY_PATH
       cd doc/daal4py
-      make html
+      make html 2>&1 | tee build.log
+      cat build.log
+      # check for autodoc warnings
+      if grep -i "autodoc" build.log; then
+          echo "Autodoc Warnings detected, build failed!"
+          exit 1
     displayName: 'Build daal4py documentation'
   - script: |
       export PREFIX=$(dirname $(dirname $(which python)))
